/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness probe checking storage and database accessibility.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version
         * @description Version and operating mode.
         */
        get: operations["version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate in exposed mode and obtain an HTTP-only session cookie.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Clear session cookie.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Samples
         * @description List bundled sample OpenAPI/Swagger specifications.
         */
        get: operations["list_samples_api_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/samples/create-project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Project From Sample
         * @description Create a new project pre-populated with a bundled sample API.
         */
        post: operations["create_project_from_sample_api_samples_create_project_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description List all projects with metadata, latest build status, and operation counts.
         */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /**
         * Create Project
         * @description Create a new empty project.
         */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project
         * @description Get project details by ID.
         */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Project
         * @description Delete project with confirmation body checking slug.
         */
        delete: operations["delete_project_api_projects__project_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Project
         * @description Update project name or slug.
         */
        patch: operations["update_project_api_projects__project_id__patch"];
        trace?: never;
    };
    "/api/projects/{project_id}/specs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Spec Versions
         * @description List all specification versions for a project.
         */
        get: operations["list_spec_versions_api_projects__project_id__specs_get"];
        put?: never;
        /**
         * Create Spec Version
         * @description Ingest a new specification version (via upload, paste, or link), preserving matching operation selections.
         */
        post: operations["create_spec_version_api_projects__project_id__specs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/specs/{vid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Spec Version
         * @description Get a specific spec version including raw text.
         */
        get: operations["get_spec_version_api_projects__project_id__specs__vid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/specs/{vid}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Diff Spec Version
         * @description Compare this spec version against another version.
         */
        get: operations["diff_spec_version_api_projects__project_id__specs__vid__diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Operations
         * @description List operations with current selection, risk labels, and user overrides.
         */
        get: operations["list_operations_api_projects__project_id__operations_get"];
        /**
         * Bulk Update Operations
         * @description Bulk update operation enabled state, tool names, descriptions, or groups.
         */
        put: operations["bulk_update_operations_api_projects__project_id__operations_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/operations/preset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply Operations Preset
         * @description Apply selection preset across all operations (read-only, all, none, by-tag).
         */
        post: operations["apply_operations_preset_api_projects__project_id__operations_preset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project Settings
         * @description Retrieve settings for a project.
         */
        get: operations["get_project_settings_api_projects__project_id__settings_get"];
        /**
         * Update Project Settings
         * @description Update settings for a project.
         */
        put: operations["update_project_settings_api_projects__project_id__settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Project
         * @description Run review engine on the latest spec version and persist findings.
         */
        post: operations["review_project_api_projects__project_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/review/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Acknowledge Findings
         * @description Acknowledge blocking error findings so that generation may proceed.
         */
        post: operations["acknowledge_findings_api_projects__project_id__review_acknowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/builds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Project Builds
         * @description List all builds for a project.
         */
        get: operations["list_project_builds_api_projects__project_id__builds_get"];
        put?: never;
        /**
         * Trigger Build
         * @description Trigger a new build for the project.
         */
        post: operations["trigger_build_api_projects__project_id__builds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/builds/{build_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Build Summary
         * @description Get single build metadata.
         */
        get: operations["get_build_summary_api_builds__build_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/builds/{build_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Files Tree
         * @description Get hierarchical file tree of generated project.
         */
        get: operations["get_files_tree_api_builds__build_id__files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/builds/{build_id}/files/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get File Content
         * @description Retrieve text content of a generated project file safely.
         */
        get: operations["get_file_content_api_builds__build_id__files_content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/builds/{build_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Build Archive
         * @description Download the deterministic ZIP artifact for a build.
         */
        get: operations["download_build_archive_api_builds__build_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/builds/{build_id}/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Connect Snippets
         * @description Get ready-to-copy client configuration snippets (Claude Desktop, Cursor, stdio, HTTP).
         */
        get: operations["get_connect_snippets_api_builds__build_id__connect_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playground/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Session
         * @description Launch a new isolated playground session.
         */
        post: operations["create_session_api_playground_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playground/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session
         * @description Get active session status and info.
         */
        get: operations["get_session_api_playground_sessions__session_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Session
         * @description Stop and terminate an active playground session.
         */
        delete: operations["delete_session_api_playground_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playground/sessions/{session_id}/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Session Tools
         * @description List available tools exposed by the session's server.
         */
        get: operations["list_session_tools_api_playground_sessions__session_id__tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playground/sessions/{session_id}/call": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Call Session Tool
         * @description Invoke an MCP tool through the playground session.
         */
        post: operations["call_session_tool_api_playground_sessions__session_id__call_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playground/sessions/{session_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Session Trace
         * @description Stream real-time protocol trace events via Server-Sent Events (SSE).
         */
        get: operations["stream_session_trace_api_playground_sessions__session_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BuildSummaryResponse */
        BuildSummaryResponse: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Spec Version Id */
            spec_version_id: string;
            /** Build No */
            build_no: number;
            /** Status */
            status: string;
            /** Tool Count */
            tool_count: number;
            /** Warning Count */
            warning_count: number;
            /** Artifact Sha256 */
            artifact_sha256?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Created At */
            created_at: string;
        };
        /**
         * CreateSessionRequest
         * @description Payload to launch a new playground session.
         */
        CreateSessionRequest: {
            /** Build Id */
            build_id: string;
            /**
             * Target
             * @default mock
             */
            target: string;
            /** Env Vars */
            env_vars?: {
                [key: string]: string;
            };
        };
        /** FileContentResponse */
        FileContentResponse: {
            /** Path */
            path: string;
            /** Content */
            content: string;
            /** Size */
            size: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Token */
            token: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Status */
            status: string;
            /** Message */
            message: string;
        };
        /**
         * OperationDiff
         * @description Diff summary of an operation between two specifications.
         */
        OperationDiff: {
            /** Operation Key */
            operation_key: string;
            /** Method */
            method: string;
            /** Path */
            path: string;
            /** Diff Type */
            diff_type: string;
            /** Changes */
            changes?: string[];
        };
        /** OperationItemResponse */
        OperationItemResponse: {
            /** Operation Key */
            operation_key: string;
            /** Method */
            method: string;
            /** Path */
            path: string;
            /** Summary */
            summary?: string | null;
            /** Description */
            description?: string | null;
            /** Tags */
            tags?: string[];
            /**
             * Deprecated
             * @default false
             */
            deprecated: boolean;
            /**
             * Risk
             * @enum {string}
             */
            risk: "read" | "write" | "destructive";
            /** Enabled */
            enabled: boolean;
            /**
             * Skipped
             * @default false
             */
            skipped: boolean;
            /** Skipped Reason */
            skipped_reason?: string | null;
            /** Tool Name */
            tool_name: string;
            /** Annotations */
            annotations?: {
                [key: string]: unknown;
            };
            /** Group */
            group?: string | null;
        };
        /** OperationUpdateItem */
        OperationUpdateItem: {
            /** Operation Key */
            operation_key: string;
            /** Enabled */
            enabled?: boolean | null;
            /** Tool Name Override */
            tool_name_override?: string | null;
            /** Description Override */
            description_override?: string | null;
            /** Group Override */
            group_override?: string | null;
        };
        /** OperationsBulkUpdateRequest */
        OperationsBulkUpdateRequest: {
            /** Operations */
            operations: components["schemas"]["OperationUpdateItem"][];
        };
        /** OperationsListResponse */
        OperationsListResponse: {
            /** Total Count */
            total_count: number;
            /** Enabled Count */
            enabled_count: number;
            /** Read Count */
            read_count: number;
            /** Write Count */
            write_count: number;
            /** Destructive Count */
            destructive_count: number;
            /** Operations */
            operations: components["schemas"]["OperationItemResponse"][];
        };
        /** OperationsPresetRequest */
        OperationsPresetRequest: {
            /**
             * Preset
             * @enum {string}
             */
            preset: "read-only" | "all" | "none" | "by-tag";
            /** Tags */
            tags?: string[] | null;
        };
        /** ProjectCreateRequest */
        ProjectCreateRequest: {
            /** Name */
            name: string;
            /** Slug */
            slug?: string | null;
        };
        /** ProjectDeleteRequest */
        ProjectDeleteRequest: {
            /** Confirm Slug */
            confirm_slug: string;
        };
        /** ProjectFromSampleRequest */
        ProjectFromSampleRequest: {
            /** Sample Id */
            sample_id: string;
            /** Name */
            name?: string | null;
            /** Slug */
            slug?: string | null;
        };
        /** ProjectResponse */
        ProjectResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Archived At */
            archived_at?: string | null;
            /**
             * Operation Count
             * @default 0
             */
            operation_count: number;
            /** Latest Build Status */
            latest_build_status?: string | null;
            /**
             * Spec Version Count
             * @default 0
             */
            spec_version_count: number;
        };
        /** ProjectSettingsResponse */
        ProjectSettingsResponse: {
            /** Project Id */
            project_id: string;
            /** Base Url */
            base_url?: string | null;
            /**
             * Timeout S
             * @default 30
             */
            timeout_s: number;
            /**
             * Max Response Chars
             * @default 20000
             */
            max_response_chars: number;
            /**
             * Retry Safe Requests
             * @default true
             */
            retry_safe_requests: boolean;
            /**
             * Max Retries
             * @default 2
             */
            max_retries: number;
            /**
             * Naming Style
             * @default snake
             */
            naming_style: string;
            /**
             * Include Writes Default
             * @default false
             */
            include_writes_default: boolean;
            /** Auth Mapping */
            auth_mapping?: {
                [key: string]: unknown;
            };
            /** Transports */
            transports?: string[];
            /** Tool Prefix */
            tool_prefix?: string | null;
        };
        /** ProjectSettingsUpdateRequest */
        ProjectSettingsUpdateRequest: {
            /** Base Url */
            base_url?: string | null;
            /** Timeout S */
            timeout_s?: number | null;
            /** Max Response Chars */
            max_response_chars?: number | null;
            /** Retry Safe Requests */
            retry_safe_requests?: boolean | null;
            /** Max Retries */
            max_retries?: number | null;
            /** Naming Style */
            naming_style?: string | null;
            /** Include Writes Default */
            include_writes_default?: boolean | null;
            /** Auth Mapping */
            auth_mapping?: {
                [key: string]: unknown;
            } | null;
            /** Transports */
            transports?: string[] | null;
            /** Tool Prefix */
            tool_prefix?: string | null;
        };
        /** ProjectUpdateRequest */
        ProjectUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Slug */
            slug?: string | null;
        };
        /** ReviewAcknowledgeRequest */
        ReviewAcknowledgeRequest: {
            /** Finding Codes */
            finding_codes?: string[];
        };
        /** ReviewFindingItem */
        ReviewFindingItem: {
            /** Id */
            id?: string | null;
            /** Code */
            code: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "error" | "warning" | "info";
            /** Message */
            message: string;
            /** Location */
            location?: string | null;
            /** Suggestion */
            suggestion?: string | null;
            /** Operation Key */
            operation_key?: string | null;
            /**
             * Acknowledged
             * @default false
             */
            acknowledged: boolean;
        };
        /** ReviewResponse */
        ReviewResponse: {
            /** Has Blocking Errors */
            has_blocking_errors: boolean;
            /** Total Findings */
            total_findings: number;
            /** Error Count */
            error_count: number;
            /** Warning Count */
            warning_count: number;
            /** Info Count */
            info_count: number;
            /** Findings */
            findings: components["schemas"]["ReviewFindingItem"][];
        };
        /** SampleSummary */
        SampleSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Filename */
            filename: string;
            /** Format */
            format: string;
            /** Operation Count */
            operation_count: number;
        };
        /** SpecCreateRequest */
        SpecCreateRequest: {
            /**
             * Source Type
             * @default paste
             * @enum {string}
             */
            source_type: "upload" | "paste" | "link";
            /** Content */
            content?: string | null;
            /** Url */
            url?: string | null;
            /** Filename */
            filename?: string | null;
        };
        /**
         * SpecDiffReport
         * @description Complete diff report between two spec versions.
         */
        SpecDiffReport: {
            /** Base Version No */
            base_version_no: number | null;
            /** Target Version No */
            target_version_no: number | null;
            /**
             * Added Count
             * @default 0
             */
            added_count: number;
            /**
             * Removed Count
             * @default 0
             */
            removed_count: number;
            /**
             * Modified Count
             * @default 0
             */
            modified_count: number;
            /**
             * Unchanged Count
             * @default 0
             */
            unchanged_count: number;
            /** Operations */
            operations?: components["schemas"]["OperationDiff"][];
            /**
             * Title Changed
             * @default false
             */
            title_changed: boolean;
            /**
             * Version Changed
             * @default false
             */
            version_changed: boolean;
            /**
             * Servers Changed
             * @default false
             */
            servers_changed: boolean;
        };
        /** SpecVersionResponse */
        SpecVersionResponse: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Version No */
            version_no: number;
            /** Source Type */
            source_type: string;
            /** Source Ref */
            source_ref?: string | null;
            /** Format */
            format: string;
            /** Spec Kind */
            spec_kind: string;
            /** Sha256 */
            sha256: string;
            /** Operation Count */
            operation_count: number;
            /** Created At */
            created_at: string;
            /** Raw Text */
            raw_text?: string | null;
        };
        /**
         * ToolCallRequest
         * @description Payload to invoke a tool within an active session.
         */
        ToolCallRequest: {
            /** Name */
            name: string;
            /** Arguments */
            arguments?: {
                [key: string]: unknown;
            };
            /**
             * Timeout S
             * @default 30
             */
            timeout_s: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_samples_api_samples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleSummary"][];
                };
            };
        };
    };
    create_project_from_sample_api_samples_create_project_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectFromSampleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectDeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_spec_versions_api_projects__project_id__specs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecVersionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_spec_version_api_projects__project_id__specs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_spec_version_api_projects__project_id__specs__vid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                vid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diff_spec_version_api_projects__project_id__specs__vid__diff_get: {
        parameters: {
            query: {
                /** @description Target version ID or version number to diff against */
                against: string;
            };
            header?: never;
            path: {
                project_id: string;
                vid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecDiffReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_operations_api_projects__project_id__operations_get: {
        parameters: {
            query?: {
                tag?: string | null;
                method?: string | null;
                risk?: string | null;
                enabled?: boolean | null;
                search?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_update_operations_api_projects__project_id__operations_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperationsBulkUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_operations_preset_api_projects__project_id__operations_preset_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperationsPresetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_settings_api_projects__project_id__settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_settings_api_projects__project_id__settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectSettingsUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_project_api_projects__project_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_findings_api_projects__project_id__review_acknowledge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewAcknowledgeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_project_builds_api_projects__project_id__builds_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildSummaryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_build_api_projects__project_id__builds_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_build_summary_api_builds__build_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                build_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_files_tree_api_builds__build_id__files_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                build_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_content_api_builds__build_id__files_content_get: {
        parameters: {
            query: {
                /** @description Relative file path within generated project */
                path: string;
            };
            header?: never;
            path: {
                build_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileContentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_build_archive_api_builds__build_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                build_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_connect_snippets_api_builds__build_id__connect_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                build_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_playground_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_playground_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_playground_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_session_tools_api_playground_sessions__session_id__tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    call_session_tool_api_playground_sessions__session_id__call_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolCallRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_session_trace_api_playground_sessions__session_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
